name: No Duplications Receiver

on: [push, pull_request]

jobs:
  nodups:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install jscpd
      run: sudo npm install -g jscpd

    - name: No Duplication beyond 3 lines
      run: jscpd --ignore "**/*.md, bms_receiver.bms_receiver_test.py" . --min-lines 3 --min-tokens 35 --threshold 0
